### ISSUE TITLE
Add `Keep` annotations to kotlin plugin example

### ISSUE THREAD

**Issue by mahesh-hegde** [dart-lang/jnigen#267]
It crashes in release mode.

```
E/flutter (32388): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception in Java code called through JNI: java.lang.NoSuchMethodError: no non-static method "LExample;.thinkBeforeAnswering(Lkotlin/coroutines/Continuation;)Ljava/lang/Object;"
E/flutter (32388):
E/flutter (32388): java.lang.NoSuchMethodError: no non-static method "LExample;.thinkBeforeAnswering(Lkotlin/coroutines/Continuation;)Ljava/lang/Object;"
E/flutter (32388):
E/flutter (32388):
E/flutter (32388): #0      JniAccessorWrappers.throwException (package:jni/src/accessors.dart:116)
E/flutter (32388): #1      _check (package:jni/src/accessors.dart:16)
E/flutter (32388): #2      JniResultMethods.check (package:jni/src/accessors.dart:21)
E/flutter (32388): #3      JniResultMethods.object (package:jni/src/accessors.dart:59)
E/flutter (32388): #4      Example.thinkBeforeAnswering (package:kotlin_plugin/kotlin_bindings.dart:61)
<Redacted>
```

**Comment by mahesh-hegde** [comment]
Edit: It has `Keep` but for some reason it's not being applied to the continuation. I am not completely familiar with the suspend fn implementation.

**Comment by mahesh-hegde** [comment]
It requires `-dontobfuscate` flag in proguard rules, because proguard obfuscates private method names.

Realized when google search returned this question https://stackoverflow.com/questions/9651703/using-proguard-with-android-without-obfuscation.
