### ISSUE TITLE
Gradle exited with status 1

### ISSUE THREAD

**Issue by efreibe** [dart-lang/jnigen#285]
> Flutter 3.10.1 • channel stable • https://github.com/flutter/flutter.git
> Framework • revision d3d8effc68 (8 days ago) • 2023-05-16 17:59:05 -0700
> Engine • revision b4fb11214d
> Tools • Dart 3.0.1 • DevTools 2.23.1

Started with a clean flutter project, first installed jnigen using this command:
> flutter pub add dev:jnigen

Then I've created the jnigen.yaml file. Ran the command:
> flutter build apk  

And then:
> dart run jnigen --config jnigen.yaml -Dlog_level=all

But I have this cryptic error:
```
$ fvm dart run jnigen --config jnigen.yaml -Dlog_level=all
(jnigen) INFO: ApiSummarizer.jar exists. Skipping build..
(jnigen) FINE: Set log level: ALL
(jnigen) INFO: trying to obtain gradle dependencies [getReleaseCompileClasspath]...
(jnigen) FINER: Writing temporary gradle script with stub "getReleaseCompileClasspath"...
(jnigen) FINER: Running gradle wrapper...
(jnigen) INFO: Restoring build scripts
Unhandled exception:


gradle exited with status 1
. This can be because the Android build is not yet cached. Please run `flutter build apk` in ./ and try again

#0      AndroidSdkTools._runGradleStub (package:jnigen/src/tools/android_sdk_tools.dart:207:7)
#1      AndroidSdkTools.getGradleClasspaths (package:jnigen/src/tools/android_sdk_tools.dart:144:7)
#2      getSummary (package:jnigen/src/summary/summary.dart:128:34)
#3      generateJniBindings (package:jnigen/src/generate_bindings.dart:25:25)
<asynchronous suspension>
#4      main (file:///Users/ernesto/.pub-cache/hosted/pub.dev/jnigen-0.4.0/bin/jnigen.dart:17:3)
<asynchronous suspension>
```

So, I've decided to run the command exactly as jnigen does, went to android folder and executed:
> ./gradlew -q getReleaseCompileClasspath

The error is:
```
$ ./gradlew -q getReleaseCompileClasspath

FAILURE: Build failed with an exception.

* What went wrong:
Task 'getReleaseCompileClasspath' not found in root project 'android'.

* Try:
> Run gradlew tasks to get a list of available tasks.
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
```

I do not know what could be wrong, but I cannot go past this error. Do I need to change something in gradle files or maybe upgrade gradle? 

Thank you all.

Here is my flutter doctor output:
```
$ flutter doctor -v        
[✓] Flutter (Channel stable, 3.10.1, on macOS 12.6.6 21G646 darwin-x64, locale en-AR)
    • Flutter version 3.10.1 on channel stable at /Users/ernesto/fvm/versions/3.10.1
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d3d8effc68 (8 days ago), 2023-05-16 17:59:05 -0700
    • Engine revision b4fb11214d
    • Dart version 3.0.1
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/ernesto/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.65.20230510

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.6.6 21G646 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Brave Browser 113.1.51.118

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

**Comment by HosseinYousefi** [comment]
> So, I've decided to run the command exactly as jnigen does, went to android folder and executed:

This won't work directly because jnigen first generates a temporary gradle script including `getReleaseCompileClasspath` and runs that instead. 

I just pushed a temporary branch, so you can see Gradle logs. Please share your `jnigen.yaml` and the logs you see here.

To use the jnigen from the temporary branch, change your pubspec.yaml like so:

```yaml
jnigen:
    git:
      url: https://github.com/dart-lang/jnigen
      path: jnigen
      ref: gradle-logs
```

**Comment by efreibe** [comment]
Hello, I've followed the instructions, added the jni package and updated the repo of the jnigen as you wrote. 

I got a new log:

```
dart run jnigen --config jnigen.yaml -Dlog_level=all
(jnigen) INFO: Building ApiSummarizer component. This might take some time. The build will be cached for subsequent runs.
(jnigen) INFO: execute mvn compile --batch-mode --update-snapshots -f /Users/ernesto/.pub-cache/git/jnigen-ee733e1719b7b7d7ee8e9746a9ecc665d99d65b9/jnigen/java/pom.xml
(jnigen) FINE: Set log level: ALL
(jnigen) INFO: trying to obtain gradle dependencies [getReleaseCompileClasspath]...
(jnigen) FINER: Writing temporary gradle script with stub "getReleaseCompileClasspath"...
(jnigen) FINER: Running gradle wrapper...
(jnigen) INFO: Restoring build scripts


FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not open cp_proj generic class cache for build file '/Users/ernesto/github/pocketcheff/api_test/android/build.gradle' (/Users/ernesto/.gradle/caches/7.5/scripts/69q432zi9qkss2bug19y08vxe).
   > BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 64

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s

Unhandled exception:


gradle exited with status 1
. This can be because the Android build is not yet cached. Please run `flutter build apk` in ./ and try again

#0      AndroidSdkTools._runGradleStub (package:jnigen/src/tools/android_sdk_tools.dart:209:7)
#1      AndroidSdkTools.getGradleClasspaths (package:jnigen/src/tools/android_sdk_tools.dart:144:7)
#2      getSummary (package:jnigen/src/summary/summary.dart:140:34)
#3      generateJniBindings (package:jnigen/src/generate_bindings.dart:29:21)
<asynchronous suspension>
#4      main (file:///Users/ernesto/.pub-cache/git/jnigen-ee733e1719b7b7d7ee8e9746a9ecc665d99d65b9/jnigen/bin/jnigen.dart:17:3)
<asynchronous suspension>
```

I was following your video un youtube, I didn't want to reinvent the wheel so I tried to reproduce the example in the video, here are the contents of my jnigen.yaml:
```
android_sdk_config:
  add_gradle_deps: true

summarizer:
  backend: asm

suspend_fun_to_async: true

output:
  c:
    library_name: health_connect
    path: src/health_connect/
  dart:
    path: lib/health_connect.dart
    structure: single_file

classes:
  - 'androidx.health.connect.client.HealthConnectClient'
  - 'android.content.Context'
```

**Comment by efreibe** [comment]
Also I put the gradle version output:
```
------------------------------------------------------------
Gradle 7.5
------------------------------------------------------------

Build time:   2022-07-14 12:48:15 UTC
Revision:     c7db7b958189ad2b0c1472b6fe663e6d654a5103

Kotlin:       1.6.21
Groovy:       3.0.10
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          20.0.1 (Homebrew 20.0.1)
OS:           Mac OS X 12.6.6 x86_64
```

**Comment by mahesh-hegde** [comment]
Looks like java version problem. The class file format error usually happens when a JVM tries to use incompatible class files (eg compiled by a later version JDK).

Try clearing you gradle caches, or setting JAVA_HOME so that all tools involved use Java 11.

We currently test on Java 11 in CI, and I think Hossein is using 17. So I would encourage to try with 11 first.

**Comment by efreibe** [comment]
@mahesh-hegde, I believe I am using the latest version of JDK:
```
$ java --version
openjdk 20.0.1 2023-04-18
OpenJDK Runtime Environment Homebrew (build 20.0.1)
OpenJDK 64-Bit Server VM Homebrew (build 20.0.1, mixed mode, sharing)
```

There is another thing I could check to get more details about the error?

**Comment by mahesh-hegde** [comment]
Your android JDK is pointing to 11. I assume that will be the one used when you run `./gradlew`.

(`./gradlew` is different from `gradle` binary in your path)

**Comment by AnisovAleksey** [comment]
I've the same error but I think it because I use flavors in android project. 
so these conditions isn't work
in `_gradleGetClasspathStub`:
```
if (variant.name.equals('release')) {
    cp += variant.javaCompile.classpath.getFiles()
}
```
in `_gradleGetSourcesStub`:
```
def componentIds = project(':app').configurations.releaseCompileClasspath.incoming
      .resolutionResult.allDependencies.collect { it.selected.id }
```

**Comment by HosseinYousefi** [comment]
@efreibe Do you get the same error if you clone https://github.com/HosseinYousefi/health_connect and run jnigen?

As @mahesh-hegde mentioned, try using a lower Java version for now, I personally use 17. I'll try to use 20 to see what the problem is.

**Comment by mahesh-hegde** [comment]
@AnisovAleksey good find. Actually we should open separate issue for that.

This gradle stuff is a bit hacky tbh.

Here's a method that will probably work: you can create a jnigen plugin and use jnigen needing to tamper with your apps gradle config. See notification_plugin_example, you will get the idea.

I'd recommend to try this.

If that's not possible, it's always possible to do away with Android SDK config and do everything manually using asm backend. Result won't be pretty though (no javadoc, no original param names [1]).

* Find where your compiled classes are in the build directory. Eg `find -name MainActivity.class`

* Find whichever JAR files you need from your local gradle cache and add that manually. (OR add the same coordinates to maven_downloads block it should also work, jnigen handles google maven repo as well.).

* Add android.jar from your android SDK folder.

The asm backend doesn't require your dependencies to be present. [2] So even if nothing of this gradle crap works, you should be able to use jnigen from basic low-level API.

---

[^fn1]: Again, you can compile classes with some specific javac option (`-parameters`?) to make it a bit better here.

[^fn2]: There's an open issue to parse java files using a more tolerant parser (maybe ECJ or QDox or `javaparser`) which does not need all dependencies to be present. That should make things better.

You may ask why there's so many edge cases here. This whole AGP/gradle ecosystem is a complexity nightmare. I have never got time to properly study it and implement gradle dependency resolution in a non-hacky way.

**Comment by AnisovAleksey** [comment]
@mahesh-hegde 
I've tried this way and still getting error. I've added prints for understand what is wrong and got that error
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not open cp_proj generic class cache for build file 'plugin/example/android/build.gradle' (/Users/user/.gradle/caches/7.5/scripts/av9st6t3cpr2rqx3uyuy58ntf).
   > BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 63

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 427ms
```

**SOLVE:** I have downgrade java version to 17 and that error was gone.

I assume need to add checks for java version because it very hard to understand that you need to downgrade java version in JAVA_HOME.
At the same time gradle tasks is working in Android studio because it has own java 17 version

**Comment by mahesh-hegde** [comment]
> I have downgrade java version to 17 and that error was gone.

That's correct, and this is a general gradle issue with java versions.

I am not sure it's possible to detect such JVM conflicts from jnigen. However we can do a better job of printing these logs.

**Comment by efreibe** [comment]
> SOLVE: I have downgrade java version to 17 and that error was gone.

That worked for me too. With version 17 it goes straight on.

**Comment by efreibe** [comment]
> However we can do a better job of printing these logs.

That will help a lot.
